url: ''
baseurl: 'https://piscespieces.github.io/lbp'
title: 'LPB.DEV'
description: "Web development agency specializing in Ruby On Rails and Full Stack Web Development"

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
